language: ruby
rvm:
- 2.2.4
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rspec
- bundle exec rubocop --config .rubocop.yml
- bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: sZNEAUGAF8pPE9/splCBk2soqp2bKJMPq0/+PMO8Xboar1d476n4Fjq0yrrxJ2kzv9P9VglELEI37+Ns6w1DkJ8Olm7VFGgblt4PUzgCjM3sDOEIBrSWIIG/MY23e6Z7lR8+0gNteIM6Zr9Ny64zKrbfvyyZ9KYpGJKHeXIZZCQTFDjphdOGVSm64m6ezOHpnj/UsesfuFARYprdyBiOMJTkgVXDQ1dnAz9/r94JJOoh7DuvJaD0JCaQyjxfg5WHXugHgjPMzDSp2aV8uNpW0/i587hjVGXABc8jSCOa74mD774Gi+EMgm9+pYN43rZoW9yPZfrXaPQ0dPhV0g9kiERhHOcLXGQkH2AXMng7lXmFvkKftiRo3Z/pUnV3R2jt/uCaumHo21KfsUXWkxMWkktip7fRDW/osub3kO2xfQ2JrlWI/LEijy1ADQ9gk3aYpxRUUCk6t/Jos9C0TaxYdhPAIcappIRHW27qkjmfFFfe/Ox1WEsmtVoSVeUKbsVzm1WOMA8PLiAMLTVGIbUNWt0Frl90TpDuTLauoav9J0+AVcSeh7aLOfZDLViBxwnJdYBBZ0RI2I0icE4ajBHd4E/GJMTyxdSqZAiqmtMY3GYw0vTR/QABrfwLczZJZeWSOIEr/Ks2pTr/CobJZKcAmdDUKo9B0xe7YHiWxajiFt0=
  app:
    production: sharemeow
    master: sharemeow-staging
  on:
    repo: producthunt/ShareMeow
